---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: debian-8.7
  - name: centos-7.3
  - name: centos-6.9
  - name: ubuntu-16.04-chef-12
    driver:
      box: bento/ubuntu-16.04
    provisioner:
      require_chef_omnibus: 12
  - name: ubuntu-14.04-chef-12
    driver:
      box: bento/ubuntu-14.04
    provisioner:
      require_chef_omnibus: 12
  - name: debian-8.7-chef-12
    driver:
      box: bento/debian-8.7
    provisioner:
      require_chef_omnibus: 12
  - name: centos-7.3-chef-12
    driver:
      box: bento/centos-7.3
    provisioner:
      require_chef_omnibus: 12
  - name: centos-6.9-chef-12
    driver:
      box: bento/centos-6.9
    provisioner:
      require_chef_omnibus: 12

suites:
  - name: default
    run_list:
      - recipe[dnsmasq-local_test]
  - name: custom
    run_list:
      - recipe[dnsmasq-local_test]
    attributes:
      dnsmasq_local:
        config:
          bind_interfaces: false
          cache_size: 64
          server:
            - 8.8.8.8
            - 8.8.4.4
          address: /example.biz/127.0.0.1
        options:
          all_servers: true
          bad_option: false
