---
driver:
  name: dokken
  privileged: true
  chef_version: latest

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  root_path: /opt/verifier
  sudo: false

platforms:
  - name: ubuntu-16.04
    driver:
      image: ubuntu:16.04
      pid_one_command: /lib/systemd/systemd
  - name: ubuntu-14.04
    driver:
      image: ubuntu:14.04
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN dpkg-divert --remove /sbin/initctl
        - RUN ln -sf /sbin/initctl.distrib /sbin/initctl
  - name: ubuntu-14.04-chef-11
    driver:
      image: ubuntu:14.04
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN dpkg-divert --remove /sbin/initctl
        - RUN ln -sf /sbin/initctl.distrib /sbin/initctl
      chef_version: 11.16.4
