---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: ubuntu-14.04-chef-11
    driver:
      box: bento/ubuntu-14.04
    provisioner:
      require_chef_omnibus: 11.16.4

suites:
  - name: default
    run_list:
      - recipe[dnsmasq-local_test]
  - name: custom
    run_list:
      - recipe[dnsmasq-local_test]
    attributes:
      dnsmasq_local:
        config:
          bind_interfaces: false
          cache_size: 64
          server:
            - 8.8.8.8
            - 8.8.4.4
          address: /example.biz/127.0.0.1
        environment:
          dnsmasq_opts: '--bind-dynamic'
