language: ruby

branches:
  only:
    - master

sudo: required

services:
  - docker

env:
  - SUITE=default PLATFORM=ubuntu
  - SUITE=default PLATFORM=debian
  - SUITE=default PLATFORM=centos
  - SUITE=custom PLATFORM=ubuntu
  - SUITE=custom PLATFORM=debian
  - SUITE=custom PLATFORM=centos
  - SUITE=remove PLATFORM=ubuntu
  - SUITE=remove PLATFORM=debian
  - SUITE=remove PLATFORM=centos

install:
  - curl -L https://www.chef.io/chef/install.sh | sudo bash -s -- -P chefdk
  - chef exec bundle install --without=development integration

before_script:
  - cp .kitchen.travis.yml .kitchen.local.yml

script:
  - chef exec bundle exec rake && chef exec bundle exec kitchen test $SUITE-$PLATFORM-
